/** AP.developv2.L4.js - RCL4 小房间策略 */
const DevelopV2_L4 = {
    CONFIG: { REFRESH_INTERVAL: 50, CREEP_CONFIG: { CommonI: { minCount: 3, maxCount: 8, bodySize: 'small' } } },
    run: function(room) { try { if(Game.time%2!==0)return; const s=this.analyze(room); this._publishCreepNeeds(room,s); } catch(e){console.log("[DevelopV2-L4] ERROR:",e);} },
    analyze:function(room){const c=this._countCreeps(room);return{rcl:room.controller.level,energyAvailable:room.energyAvailable,creeps:c,commonICount:c.CommonI||0,controllerProgress:room.controller.progress/room.controller.progressTotal,storageBuilt:!!room.storage};},
    _publishCreepNeeds:function(room,state){const tb=require('lib.AP.taskboard'),cfg=this.CONFIG.CREEP_CONFIG.CommonI;if(state.commonICount>=cfg.maxCount)return;if(state.commonICount<cfg.minCount&&!this._hasPendingNeed(room.name,'CommonI'))tb.strategy.needCreeps(room.name,{model:'CommonI',count:cfg.minCount-state.commonICount,priority:'harvest',data:{bodySize:cfg.bodySize}});this._publishRepairTasks(tb,room);this._publishCreepTasks(tb,room.name,'harvest',2);this._publishCreepTasks(tb,room.name,'upgrade',2);},
    _publishRepairTasks:function(taskboard,room){const towers=room.find(FIND_MY_STRUCTURES,{filter:s=>s.structureType===STRUCTURE_TOWER});const hasTower=towers.length>0;const count=hasTower?1:2;const damagedNormal=room.find(FIND_STRUCTURES,{filter:s=>s.hits<s.hitsMax&&s.structureType!==STRUCTURE_WALL&&s.structureType!==STRUCTURE_RAMPART});const damagedWalls=room.find(FIND_STRUCTURES,{filter:s=>(s.structureType===STRUCTURE_WALL||s.structureType===STRUCTURE_RAMPART)&&s.hits<10000});if(damagedNormal.length>0||damagedWalls.length>0){let existing=taskboard.getTasks(room.name,'Creeps');let cur=0;for(let i=0;i<existing.length;i++)if(existing[i].type==='repair')cur++;const toAdd=count-cur;for(let j=0;j<toAdd;j++)taskboard._addTask('Creeps',room.name,'repair',{autoAssign:true});}},
    _publishCreepTasks:function(tb,roomName,taskType,targetCount){var existing=tb.getTasks(roomName,'Creeps');var cnt=0;for(var i=0;i<existing.length;i++){if(existing[i].type===taskType)cnt++;}for(var j=cnt;j<targetCount;j++){tb._addTask('Creeps',roomName,taskType,{autoAssign:true});}},
    _hasPendingNeed:function(roomName,model){if(!Memory.Taskboard||!Memory.Taskboard.Task||!Memory.Taskboard.Task.Strategy)return false;var t=Memory.Taskboard.Task.Strategy[roomName];if(!Array.isArray(t))return false;for(var i=0;i<t.length;i++){if(t[i].type==='needCreeps'&&t[i].data&&t[i].data.model===model)return true;}return false;},
    _countCreeps:function(room){const o={CommonI:0,CarrierI:0,AttackerI:0,ClaimerI:0};for(const c of room.find(FIND_MY_CREEPS))if(c.memory.model&&o[c.memory.model]!==undefined)o[c.memory.model]++;return o;}
};
module.exports=DevelopV2_L4;
